### ISSUE TITLE
CAN Gateway login

### ISSUE THREAD

**Issue by DiagProf** [gmenounos/vwcluster#4]
First of all, thank you for the good information. 
You wrote the following...
>The CAN Gateway accepts one login value. This value is stored at EEPROM addresses $13C-$13D and is typically 10777. It has not yet been determined what this login is used for.

If I remember correctly, I read somewhere that code 10777 switches a small relay on the PCB of your dashboard. When you enter the code, you should hear a relay switch (of course, only if it's very, very quiet). 
Although your car diagnostic uses K-Line, there should also be a CAN bus present at the diagnostic connector. The CAN lines run from the diagnostic connector to the instrument cluster but are essentially inactive. When the relay is activated, the Powertrain-CAN   is routed to these lines.

But I believe the relay disappears after a very short time. If you want to keep it activated for longer, you need to send a specific CAN message from the diagnostic connector side, which I don’t know.

Without guarantee. :-)

By the way in the dashboard (address 0x17), the normal login 13861 should still be found, which is meant to protect the adaptation channel 09 from accidental changes.

**Comment by gmenounos** [comment]
Thanks for the useful info! I'll do some experimentation and then document this in more detail.
